// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsVJzgshE2uUkvAnOiMN-lrDk6TMsWSjQ',
    appId: '1:218356139445:web:b93b8a3fb76180353dc5fc',
    messagingSenderId: '218356139445',
    projectId: 'toughtchain',
    authDomain: 'toughtchain.firebaseapp.com',
    storageBucket: 'toughtchain.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR7j6lGMUoAnddnqIMbsP4s_D6zv8zO0k',
    appId: '1:218356139445:android:4ebf48e0b306d02f3dc5fc',
    messagingSenderId: '218356139445',
    projectId: 'toughtchain',
    storageBucket: 'toughtchain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPXwPgSuwy1TyzmVTC3g7z9-b0qlXBm8Y',
    appId: '1:218356139445:ios:bc1971738276f1da3dc5fc',
    messagingSenderId: '218356139445',
    projectId: 'toughtchain',
    storageBucket: 'toughtchain.firebasestorage.app',
    iosBundleId: 'com.example.toughtchainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPXwPgSuwy1TyzmVTC3g7z9-b0qlXBm8Y',
    appId: '1:218356139445:ios:bc1971738276f1da3dc5fc',
    messagingSenderId: '218356139445',
    projectId: 'toughtchain',
    storageBucket: 'toughtchain.firebasestorage.app',
    iosBundleId: 'com.example.toughtchainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsVJzgshE2uUkvAnOiMN-lrDk6TMsWSjQ',
    appId: '1:218356139445:web:4b6c4f6b56dd0bdb3dc5fc',
    messagingSenderId: '218356139445',
    projectId: 'toughtchain',
    authDomain: 'toughtchain.firebaseapp.com',
    storageBucket: 'toughtchain.firebasestorage.app',
  );
}
